#!/bin/bash

for i in `fastboot devices | grep fastboot | awk '{print $1}'`; do echo $i;

read -p "[Press enter to continue]"

for i in `fastboot devices | grep fastboot | awk '{print $1}'`; do bash flashTarget.sh $i & done
