#!/bin/bash

INDEX=0
for i in `fastboot devices | grep fastboot | awk '{print $1}'`; do
let INDEX=${INDEX}+1
echo Device[${INDEX}] $i
done

read -p "[Press ENTER to continue]"

INDEX=0
for i in `fastboot devices | grep fastboot | awk '{print $1}'`; do
let INDEX=${INDEX}+1
bash flashTarget.sh $i $INDEX &
done
