#!/bin/bash

INDEX=0
for i in `sudo fastboot devices | grep fastboot | awk '{print $1}'`; do
let INDEX=${INDEX}+1
echo Device[${INDEX}] $i
done

ls $1*.img

read -p "[Press ENTER to flash $INDEX devices]"

INDEX=0
for i in `sudo fastboot devices | grep fastboot | awk '{print $1}'`; do
let INDEX=${INDEX}+1
bash flashTarget.sh $i $INDEX $1 &
done
